---

- name: install packages
  apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
          cache_valid_time: 3600
  with_items:
          - nginx
          - ruby
          - ruby-dev
          - make
          - gcc

- name: Copy over nginx configs
  template:
          src: "{{ item }}"
          dest: "/etc/nginx/{{ item }}"
  with_items:
          - nginx.conf
          - ssl-params.conf
  notify: restart nginx

- name: remove default nginx site
  file:
          path: /etc/nginx/sites-enabled/default
          state: absent
  notify: restart nginx

- name: enable nginx on boot
  service:
          name: nginx
          enabled: yes

- name: Copy over nginx site configs
  template:
          src: "{{ item }}"
          dest: "/etc/nginx/sites-enabled/"
  with_items:
          - www.zoneminder.com.conf
          - telemetry.zoneminder.com.conf
          - update.zoneminder.com.conf
  notify: restart nginx
  tags: web

- name: Create webroots
  file:
          path: "/var/www/{{ item }}"
          state: directory
          owner: www-data
          group: www-data
  with_items:
          - www.zoneminder.com
          - update.zoneminder.com
          - telemetry.zoneminder.com

- name: update.zoneminder.com cron job
  cron: name="version.txt" user="root"  minute="*/15" job='#wget -q https://raw.githubusercontent.com/ZoneMinder/ZoneMinder/master/version -O /var/www/update.zoneminder.com/version.txt && curl https://nosnch.in/bc25ce264b &> /dev/null'

- name: Clone the site
  git:
          repo: https://github.com/ZoneMinder/zoneminder.github.io.git
          dest: "{{ git_dest }}"
          version: master

- name: Install gems needed for jekyll
  gem:
          name: "{{ item }}"
          state: present
          user_install: no
  with_items:
          - jekyll
          - bundler
          - html-proofer

- name: Build the site
  command: bundle exec jekyll build
  args:
          chdir: "{{ git_dest }}"
