---

- name: Copy over nginx configs
  template:
          src: "{{ item }}"
          dest: "/etc/nginx/{{ item }}"
  with_items:
          - nginx.conf
          - ssl-params.conf
  notify: restart nginx

- name: install packages
  apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
          cache_valid_time: 3600
  with_items:
    - nginx

- name: remove default nginx site
  file:
          path: /etc/nginx/sites-enabled/default
          state: absent
  notify: restart nginx

- name: enable nginx on boot
  service:
          name: nginx
          state: enabled

- name: Copy over nginx site configs
  template: src=www.zoneminder.com.conf dest=/etc/nginx/sites-enabled/www.zoneminder.com.conf
  template:
          src: "{{ item }}"
          dest: "/etc/nginx/sites-enabled/"
  with_items:
          - www.zoneminder.com.conf
          - telemetry.zoneminder.com.conf
          - update.zoneminder.com.conf
  notify: restart nginx
  tags: web

- name: Create webroots
  file:
          path: "/var/www/{{ item }}"
          state: directory
          owner: www-data
          group: www-data
  with_items:
          - www.zoneminder.com
          - update.zoneminder.com
          - telemetry.zoneminder.com

- name: update.zoneminder.com cron job
  cron: name="version.txt" user="root"  minute="*/15" job='#wget -q https://raw.githubusercontent.com/ZoneMinder/ZoneMinder/master/version -O /var/www/update.zoneminder.com/version.txt && curl https://nosnch.in/bc25ce264b &> /dev/null'
